name: play-with-actions

#on: [push]
on:
  schedule:
    - cron: '20 14 * * *'
  push:
    branches: [master]
    tags:
      - 'v*.*.*'

env:
  DOCKER_REPO: site2

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: checking out repo
        uses: actions/checkout@v3
      - run: echo "post-checkout" && ls -lah && pwd
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            name/app
            ghcr.io/username/app
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: docker buildx
        uses: docker/setup-buildx-action@v1
      - name: build and push
        uses: docker/build-push-action@v2
        with:
           tags: ${{ steps.meta.outputs.tags }}
          #tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest,${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:2.0
          #labels: ${{ steps.meta.outputs.labels }} 
         # push: true
         # tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:latest,${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:2.0
